//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIES()
        {
            this.PROGRAM = new HashSet<PROGRAM>();
        }
    
        public string ID_MOVIE { get; set; }
        public string TITLE { get; set; }
        public string GENRE { get; set; }
        public System.TimeSpan RUNTIME { get; set; }
        public byte RATING { get; set; }
        public Nullable<System.DateTime> RELEASE_DATE { get; set; }
        public string DIRECTION { get; set; }
        public string SCREENPLAY { get; set; }
        public string STARRING { get; set; }
        public string IMAGE { get; set; }
        public string TRAILER { get; set; }
        public string SYNOPSIS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROGRAM> PROGRAM { get; set; }
    }
}
