//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATIONS_DETAILS
    {
        public short ID_RESERVATION { get; set; }
        public string ID_SEAT { get; set; }
        public byte ID_TICKET { get; set; }
    
        public virtual RESERVATIONS RESERVATIONS { get; set; }
        public virtual TICKETS TICKETS { get; set; }
    }
}
