//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TICKETS()
        {
            this.RESERVATIONS_DETAILS = new HashSet<RESERVATIONS_DETAILS>();
        }
    
        public byte ID_TICKET { get; set; }
        public string TYPE { get; set; }
        public decimal PRICE_2D { get; set; }
        public decimal PRICE_3D { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATIONS_DETAILS> RESERVATIONS_DETAILS { get; set; }
    }
}
