//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Client
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.RESERVATIONS = new HashSet<RESERVATIONS>();
        }

        [Required(ErrorMessage = "To pole jest wymagane!")]
        public string USER_LOGIN { get; set; }

        [Required(ErrorMessage = "To pole jest wymagane!")]
        [DataType(DataType.Password)]
        public string PASSWORD { get; set; }

        [Required(ErrorMessage = "To pole jest wymagane!")]
        public string NAME { get; set; }

        [Required(ErrorMessage = "To pole jest wymagane!")]
        public string SURNAME { get; set; }

        [Required(ErrorMessage = "To pole jest wymagane!")]
        [RegularExpression(@"^[a-zA-Z0-9._-]+@[a-zA-Z0-9-]+\.[a-zA-Z]{2,4}", ErrorMessage = "Podaj poprawny adres e-mail!")]
        public string E_MAIL { get; set; }

        [Required(ErrorMessage = "To pole jest wymagane!")]
        [RegularExpression(@"^[0-9]{9}", ErrorMessage = "Podaj poprawny numer telefonu!")]
        public string TELEPHONE { get; set; }

        public Nullable<System.DateTime> LAST_LOGIN { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATIONS> RESERVATIONS { get; set; }

    }
}