//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINS
    {
        public string ADMIN_LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string E_MAIL { get; set; }
        public string TELEPHONE { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN { get; set; }
        public Nullable<System.DateTime> LAST_LOGOUT { get; set; }
    }
}
