//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVATIONS()
        {
            this.RESERVATIONS_DETAILS = new HashSet<RESERVATIONS_DETAILS>();
        }
    
        public short ID_RESERVATION { get; set; }
        public short ID_PROGRAM { get; set; }
        public string USER_LOGIN { get; set; }
    
        public virtual PROGRAM PROGRAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATIONS_DETAILS> RESERVATIONS_DETAILS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
